### PR TITLE
young adult income

### PR DESCRIPTION
**Pull request by Pavan1007**
Change young adult flag in state config file. 

Test results:

Finished in 1.63031s
326 tests, 1521 assertions, 0 failures, 0 errors, 0 skips

Rspec results: 

Finished in 0.49998 seconds (files took 1.72 seconds to load)
135 examples, 0 failures

### CODE REVIEW

**Comment by venu211** [comment]
Pavan the following test cases are failing and the Options Young adult flag should be "N"  for the sake of core 24 test cases.


Failures:

  1) Test cases for all Core 24 Json files test_QACORE8MAGIIAUA004_married_filing_separately_big_household behaves like Core 24 tests Compares Medicaid Eligibilty 
     Failure/Error: expect(applicant['Medicaid Eligible']).to eq @person[index][:MedicaidEligible]
     
       expected: "N"
            got: "Y"
     
       (compared using ==)
     Shared Example Group: "Core 24 tests" called from ./spec/core24_specs/core24_spec.rb:79
     # ./spec/core24_specs/core24_spec.rb:26:in `block (4 levels) in <top (required)>'
     # ./spec/core24_specs/core24_spec.rb:25:in `each'
     # ./spec/core24_specs/core24_spec.rb:25:in `each_with_index'
     # ./spec/core24_specs/core24_spec.rb:25:in `block (3 levels) in <top (required)>'

  2) Test cases for all Core 24 Json files test_QACORE8MAGIIAUA004_married_filing_separately_big_household behaves like Core 24 tests Compares APTC Referal
     Failure/Error: expect(applicant['Determinations']['APTC Referral']['Indicator']).to eq @person[index][:APTCReferal]
     
       expected: "Y"
            got: "N"
     
       (compared using ==)
     Shared Example Group: "Core 24 tests" called from ./spec/core24_specs/core24_spec.rb:79
     # ./spec/core24_specs/core24_spec.rb:38:in `block (4 levels) in <top (required)>'
     # ./spec/core24_specs/core24_spec.rb:37:in `each'
     # ./spec/core24_specs/core24_spec.rb:37:in `each_with_index'
     # ./spec/core24_specs/core24_spec.rb:37:in `block (3 levels) in <top (required)>'

  3) Test cases for all Core 24 Json files test_QACORE2IA009 behaves like Core 24 tests Compares Medicaid Eligibilty 
     Failure/Error: expect(applicant['Medicaid Eligible']).to eq @person[index][:MedicaidEligible]
     
       expected: "N"
            got: "Y"
     
       (compared using ==)
     Shared Example Group: "Core 24 tests" called from ./spec/core24_specs/core24_spec.rb:173
     # ./spec/core24_specs/core24_spec.rb:26:in `block (4 levels) in <top (required)>'
     # ./spec/core24_specs/core24_spec.rb:25:in `each'
     # ./spec/core24_specs/core24_spec.rb:25:in `each_with_index'
     # ./spec/core24_specs/core24_spec.rb:25:in `block (3 levels) in <top (required)>'

  4) Test cases for all Core 24 Json files test_QACORE2IA009 behaves like Core 24 tests Compares APTC Referal
     Failure/Error: expect(applicant['Determinations']['APTC Referral']['Indicator']).to eq @person[index][:APTCReferal]
     
       expected: "Y"
            got: "N"
     
       (compared using ==)
     Shared Example Group: "Core 24 tests" called from ./spec/core24_specs/core24_spec.rb:173
     # ./spec/core24_specs/core24_spec.rb:38:in `block (4 levels) in <top (required)>'
     # ./spec/core24_specs/core24_spec.rb:37:in `each'
     # ./spec/core24_specs/core24_spec.rb:37:in `each_with_index'
     # ./spec/core24_specs/core24_spec.rb:37:in `block (3 levels) in <top (required)>'

Finished in 0.56719 seconds (files took 1.59 seconds to load)
135 examples, 4 failures

Failed examples:

rspec ./spec/core24_specs/core24_spec.rb[1:2:1:2] # Test cases for all Core 24 Json files test_QACORE8MAGIIAUA004_married_filing_separately_big_household behaves like Core 24 tests Compares Medicaid Eligibilty 
rspec ./spec/core24_specs/core24_spec.rb[1:2:1:4] # Test cases for all Core 24 Json files test_QACORE8MAGIIAUA004_married_filing_separately_big_household behaves like Core 24 tests Compares APTC Referal
rspec ./spec/core24_specs/core24_spec.rb[1:10:1:2] # Test cases for all Core 24 Json files test_QACORE2IA009 behaves like Core 24 tests Compares Medicaid Eligibilty 
rspec ./spec/core24_specs/core24_spec.rb[1:10:1:4] # Test cases for all Core 24 Json files test_QACORE2IA009 behaves like Core 24 tests Compares APTC Referal

**Comment by venu211** [comment]
Test are failing on my local QA branch there is something wrong with Origin/qa branch on github. May be we need to figure this out.

**Comment by Pavan1007** [comment]
Okay, as discussed in the git standards meeting we are supposed to create a new branch based on the 'qa' branch and do the changes. So I created a 'young_adult' branch based on 'qa' branch and did the changes. The tests were passing in both young_adult and qa branch and if it fails in master branch then I think something is wrong with the master/qa sync. Someone needs to recheck the branching in MITC.

**Comment by venu211** [comment]
@Pavan1007 I will recheck the branch.

**Comment by venu211** [comment]
Keep this PR in pending until we fix the branching issue.

**Comment by Pavan1007** [comment]
I modified the code and tested it against master branch. All the tests are passing now and I will push the code once you are done with master/qa branch fix. Please let me know once it is done.

**Comment by venu211** [comment]
@Pavan1007 We are working on it, will let you know and you should create a new PR with the modified code after we resolved this issue.

**Comment by Pavan1007** [comment]
@venu211 Of course

**Comment by venu211** [comment]
@Pavan1007 and @bommurevathi7 The issue is resolved. I am approving the PR. Please comment the test results for one more time.

**Comment by Pavan1007** [comment]
@venu211 nice! here you go, please find the test results below.

Test results:
Finished in 1.65280s
326 tests, 1521 assertions, 0 failures, 0 errors, 0 skips

Rspec Results:
Finished in 0.45929 seconds (files took 1.39 seconds to load)
135 examples, 0 failures

**Pull request merged**
